apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    uid: srne-influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: ${INFLUXDB2_ORG}
      defaultBucket: ${INFLUXDB2_BUCKET}
      tlsSkipVerify: true
    secureJsonData:
      token: ${INFLUXDB2_TOKEN}
    editable: false
