#!/bin/bash
# Opt-in: enable the "Restart Host" button in the modbus_api UI.
#
# Installs a systemd path unit that watches a sentinel file in
# /var/lib/srne-reboot/.  When the container creates that file (via
# POST /restart_host), the unit fires and reboots the host.
#
# Also writes compose.override.yaml so the next `docker compose up -d`
# bind-mounts the sentinel directory into modbus_api.
#
# Re-run safely; this script overwrites its own outputs.

set -euo pipefail

if [[ $EUID -ne 0 ]]; then
    echo "Must be run as root (sudo)." >&2
    exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

SENTINEL_DIR="/var/lib/srne-reboot"
TRIGGER_SCRIPT="/usr/local/sbin/srne-reboot.sh"
PATH_UNIT="/etc/systemd/system/srne-reboot.path"
SERVICE_UNIT="/etc/systemd/system/srne-reboot.service"
OVERRIDE_FILE="${PROJECT_DIR}/compose.override.yaml"

echo "Creating sentinel directory ${SENTINEL_DIR}"
mkdir -p "${SENTINEL_DIR}"
# World-writable: the modbus_api container's UID is not pinned, and this dir
# only ever holds a single zero-byte trigger file. Personal-use system.
chmod 0777 "${SENTINEL_DIR}"

echo "Writing ${TRIGGER_SCRIPT}"
cat > "${TRIGGER_SCRIPT}" <<'EOF'
#!/bin/bash
# Triggered by srne-reboot.path when the container writes the sentinel file.
#
# Cooldown safety: refuses to reboot if the previous reboot was less than
# COOLDOWN_SECONDS ago. The timestamp file persists across reboots, so a
# malfunction that re-creates the trigger immediately after boot cannot
# loop the host. Manual override:
#   sudo rm /var/lib/srne-reboot/last-reboot   # forget the last reboot
#   sudo systemctl disable --now srne-reboot.path   # stop the watcher
set -e

TRIGGER=/var/lib/srne-reboot/reboot-requested
LAST=/var/lib/srne-reboot/last-reboot
COOLDOWN_SECONDS=3600   # 60 minutes — edit and re-run install if you want a different value

# Always remove the trigger first, even when suppressing — otherwise the
# path unit would re-fire as soon as the trigger reappears.
rm -f "$TRIGGER"

now=$(date +%s)
if [[ -f "$LAST" ]]; then
    last=$(cat "$LAST" 2>/dev/null || echo 0)
    elapsed=$(( now - last ))
    if (( elapsed < COOLDOWN_SECONDS )); then
        logger -t srne-reboot "reboot suppressed by cooldown (${elapsed}s < ${COOLDOWN_SECONDS}s)"
        exit 0
    fi
fi

echo "$now" > "$LAST"
logger -t srne-reboot "reboot triggered (cooldown=${COOLDOWN_SECONDS}s)"
sleep 5
/sbin/shutdown -r now
EOF
chmod 0755 "${TRIGGER_SCRIPT}"

echo "Writing ${PATH_UNIT}"
cat > "${PATH_UNIT}" <<'EOF'
[Unit]
Description=Watch for srne reboot request

[Path]
PathExists=/var/lib/srne-reboot/reboot-requested
Unit=srne-reboot.service

[Install]
WantedBy=multi-user.target
EOF

echo "Writing ${SERVICE_UNIT}"
cat > "${SERVICE_UNIT}" <<'EOF'
[Unit]
Description=Reboot host on srne container request

[Service]
Type=oneshot
ExecStart=/usr/local/sbin/srne-reboot.sh
EOF

echo "Reloading systemd and enabling srne-reboot.path"
systemctl daemon-reload
systemctl enable --now srne-reboot.path

echo "Writing ${OVERRIDE_FILE}"
cat > "${OVERRIDE_FILE}" <<'EOF'
# Auto-generated by scripts/install-host-reboot.sh.
# Removed by scripts/uninstall-host-reboot.sh. Do not edit.
services:
  modbus_api:
    volumes:
      - /var/lib/srne-reboot:/var/run/srne-reboot
EOF

echo
echo "Installed. Now run:  docker compose up -d"
