#!/bin/bash
# Opt-in: enable the "Restart Host" button in the modbus_api UI.
#
# Installs a systemd path unit that watches a sentinel file in
# /var/lib/srne-reboot/.  When the container creates that file (via
# POST /restart_host), the unit fires and reboots the host.
#
# Also writes compose.override.yaml so the next `docker compose up -d`
# bind-mounts the sentinel directory into modbus_api.
#
# Re-run safely; this script overwrites its own outputs.

set -euo pipefail

if [[ $EUID -ne 0 ]]; then
    echo "Must be run as root (sudo)." >&2
    exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

SENTINEL_DIR="/var/lib/srne-reboot"
TRIGGER_SCRIPT="/usr/local/sbin/srne-reboot.sh"
PATH_UNIT="/etc/systemd/system/srne-reboot.path"
SERVICE_UNIT="/etc/systemd/system/srne-reboot.service"
OVERRIDE_FILE="${PROJECT_DIR}/compose.override.yaml"

echo "Creating sentinel directory ${SENTINEL_DIR}"
mkdir -p "${SENTINEL_DIR}"
# World-writable: the modbus_api container's UID is not pinned, and this dir
# only ever holds a single zero-byte trigger file. Personal-use system.
chmod 0777 "${SENTINEL_DIR}"

echo "Writing ${TRIGGER_SCRIPT}"
cat > "${TRIGGER_SCRIPT}" <<'EOF'
#!/bin/bash
# Triggered by srne-reboot.path when the container writes the sentinel file.
set -e
rm -f /var/lib/srne-reboot/reboot-requested
logger -t srne-reboot "host reboot requested by container"
sleep 5
/sbin/shutdown -r now
EOF
chmod 0755 "${TRIGGER_SCRIPT}"

echo "Writing ${PATH_UNIT}"
cat > "${PATH_UNIT}" <<'EOF'
[Unit]
Description=Watch for srne reboot request

[Path]
PathExists=/var/lib/srne-reboot/reboot-requested
Unit=srne-reboot.service

[Install]
WantedBy=multi-user.target
EOF

echo "Writing ${SERVICE_UNIT}"
cat > "${SERVICE_UNIT}" <<'EOF'
[Unit]
Description=Reboot host on srne container request

[Service]
Type=oneshot
ExecStart=/usr/local/sbin/srne-reboot.sh
EOF

echo "Reloading systemd and enabling srne-reboot.path"
systemctl daemon-reload
systemctl enable --now srne-reboot.path

echo "Writing ${OVERRIDE_FILE}"
cat > "${OVERRIDE_FILE}" <<'EOF'
# Auto-generated by scripts/install-host-reboot.sh.
# Removed by scripts/uninstall-host-reboot.sh. Do not edit.
services:
  modbus_api:
    volumes:
      - /var/lib/srne-reboot:/var/run/srne-reboot
EOF

echo
echo "Installed. Now run:  docker compose up -d"
